[project]
name = "pixel-alchemy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "NoRaincheck", email = "2498638+NoRaincheck@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "huggingface_hub>=0.20.0",
    "onnx>=1.22.0",
    "onnxruntime>=1.27.0",
    "opencv-python-headless>=5.0.0.93",
    "pillow>=12.3.0",
    "sh>=2.3.0",
    "vtracer>=0.6.15",
]

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "deno>=2.9.4",
    "pytest>=9.1.1",
    "ruff>=0.16.0",
    "ty>=0.0.63",
]

[tool.ruff]
line-length = 120
