"""Song file handling — port of App/services/song.py (Sonic Pi path rewriting)."""

from __future__ import annotations

import os
import re
from pathlib import Path

from .song_data import SongCreationData


class Song:
    def __init__(self, name: str, base_dir: str | Path = "songs"):
        self.name = name
        self.base_dir = Path(base_dir)

    def get_song_dir(self) -> Path:
        d = self.base_dir / self.name
        d.mkdir(parents=True, exist_ok=True)
        return d

    @property
    def song_dir(self) -> Path:
        return self.get_song_dir()

    def create_song_file(self, data: SongCreationData) -> Path:
        code = data.sonicpi_code or ""
        header = f"# --{self.name.upper()}-- \n# Generated by MusicAgent (pixel-alchemy)\n"
        if not code.startswith(header):
            code = header + code

        # inject absolute sample paths for Sonic Pi if sample "foo/bar.wav" is relative
        # keep already absolute paths
        samples_root = (Path.cwd() / "samples").resolve()
        # alternative: use base_dir sibling samples if exists
        def _replace(m: re.Match) -> str:
            rel = m.group(1)
            # if already absolute, keep
            if os.path.isabs(rel):
                return m.group(0)
            # try to resolve to absolute fs path
            abs_path = (samples_root / rel).as_posix()
            # also try project samples/sounds
            if not Path(abs_path).exists():
                alt = (Path.cwd() / "samples" / "sounds" / rel).as_posix()
                if Path(alt).exists():
                    abs_path = alt
            return f'sample "{abs_path}"'

        # only rewrite if looks like a sample pool path (contains / or .wav/.ogg)
        # we keep simple: rewrite non-absolute sample "x"
        final_code = re.sub(r'sample\s+"([^"]+)"', _replace, code)

        out = self.get_song_dir() / f"{self.name}.rb"
        # versioning: keep old file
        if out.exists():
            old = out.read_text(encoding="utf-8", errors="ignore")
            if old != final_code:
                i = 1
                while (self.get_song_dir() / f"{self.name}_{i}.rb").exists():
                    i += 1
                out.rename(self.get_song_dir() / f"{self.name}_{i}.rb")
        out.write_text(final_code, encoding="utf-8")
        return out

    def create_readme(self, data: SongCreationData) -> Path:
        out = self.get_song_dir() / "README.md"
        out.write_text(
            f"# {self.name}\n\n"
            f"**Description:** {data.song_description}\n\n"
            f"**Structure:** {data.structure}\n\n"
            f"**Theme:** {data.theme}\n\n"
            f"**Melody:** {data.melody}\n\n"
            f"**Rhythm:** {data.rhythm}\n\n"
            f"**Arrangements:** {data.arrangements}\n\n"
            f"**Segments:** {data.segments}\n\n"
            f"**Duration:** {data.total_duration}s\n\n",
            encoding="utf-8",
        )
        return out
